# Generated by Django 3.0.3 on 2020-08-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_readnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='REadNum',
        ),
    ]
